language: cpp
sudo: required
os: linux
dist: trusty

compiler:
  - clang
  
  before_script:
  - sudo apt-get install
  
  install:
  - wget https://downloads.codelite.org/downloads.php?ubuntu_1804_64_weekly
  - sudo dpkg -i CodeLite-12.0.3-gtk2-ubuntu-bionic-x86_64.deb
