language: cpp
sudo: required
os: linux
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
dist: trusty

compiler:
- clang
  
before_script:
- sudo apt-get install
  
install:
- sudo apt-get install gdebi-core
- wget -O Codelite.deb https://downloads.codelite.org/downloads.php?ubuntu_1804_64_weekly
- sudo gdebi Codelite.deb
- sudo dpkg -i Codelite.deb

script:
- python PyBuild.py
